### ISSUE TITLE
Installation issue with No matching distribution found for docker-compose-wait error

### ISSUE THREAD

**Issue by Binamebou** [nicolas-van/docker-compose-wait#10]
On CentOs 7 
python.x86_64 0:2.7.5-68.el7
pip-10.0.1
docker-compose version 1.21.2, build a133471
docker-py version: 3.3.0
CPython version: 3.6.5

When installing 

pip install docker-compose-wait
Collecting docker-compose-wait
  Could not find a version that satisfies the requirement docker-compose-wait (from versions: )
No matching distribution found for docker-compose-wait

Same error when using sudo

**Comment by nicolas-van** [comment]
Fixed in version 1.0.2
